truncate authors cascade;

insert into authors (id, first_name, last_name, description) values (1, 'Page', 'Haig', 'some description');
insert into authors (id, first_name, last_name, description) values (2, 'Thorstein', 'Pohlke', 'some description');
insert into authors (id, first_name, last_name, description) values (3, 'Zaccaria', 'Tolomelli', 'some description');
insert into authors (id, first_name, last_name, description) values (4, 'Annalise', 'Willshee', 'some description');
insert into authors (id, first_name, last_name, description) values (5, 'Alejandrina', 'Bonhomme', 'some description');
insert into authors (id, first_name, last_name, description) values (6, 'Myrna', 'Samber', 'some description');
insert into authors (id, first_name, last_name, description) values (7, 'Aida', 'Phelips', 'some description');
insert into authors (id, first_name, last_name, description) values (8, 'Cherise', 'Rolley', 'some description');
insert into authors (id, first_name, last_name, description) values (9, 'Townie', 'Ream', 'some description');
insert into authors (id, first_name, last_name, description) values (10, 'Barbabas', 'Hairesnape', 'some description');
insert into authors (id, first_name, last_name, description) values (11, 'Fifine', 'Swinley', 'some description');
insert into authors (id, first_name, last_name, description) values (12, 'Elia', 'Cribbins', 'some description');
insert into authors (id, first_name, last_name, description) values (13, 'Mirelle', 'Dax', 'some description');
insert into authors (id, first_name, last_name, description) values (14, 'Lee', 'Fronsek', 'some description');
insert into authors (id, first_name, last_name, description) values (15, 'Angelina', 'Goulstone', 'some description');
insert into authors (id, first_name, last_name, description) values (16, 'Venita', 'Peltz', 'some description');
insert into authors (id, first_name, last_name, description) values (17, 'Antonin', 'Le', 'some descriptionClaire');
insert into authors (id, first_name, last_name, description) values (18, 'Peta', 'Garnson', 'some description');
insert into authors (id, first_name, last_name, description) values (19, 'Berte', 'Upchurch', 'some description');
insert into authors (id, first_name, last_name, description) values (20, 'Maurizia', 'Abramzon', 'some description');
insert into authors (id, first_name, last_name, description) values (21, 'Neddy', 'Wathall', 'some description');



insert into books (id, price, price_old, title, author_id) values (1, 681, 3938, 'Stim', 20);
insert into books (id, price, price_old, title, author_id) values (2, 1860, 2050, 'Domainer', 7);
insert into books (id, price, price_old, title, author_id) values (3, 1091, 3712, 'Bamity', 5);
insert into books (id, price, price_old, title, author_id) values (4, 1688, 2374, 'Fix San', 3);
insert into books (id, price, price_old, title, author_id) values (5, 2802, 3976, 'Solarbreeze', 14);
insert into books (id, price, price_old, title, author_id) values (6, 1368, 1908, 'Wrapsafe', 5);
insert into books (id, price, price_old, title, author_id) values (7, 2711, 3437, 'Bigtax', 2);
insert into books (id, price, price_old, title, author_id) values (8, 2790, 3726, 'Voyatouch', 17);
insert into books (id, price, price_old, title, author_id) values (9, 2066, 1548, 'Span', 6);
insert into books (id, price, price_old, title, author_id) values (10, 2480, 2606, 'Tin', 6);
insert into books (id, price, price_old, title, author_id) values (11, 1962, 3561, 'Overhold', 9);
insert into books (id, price, price_old, title, author_id) values (12, 1989, 2544, 'Alphazap', 9);
insert into books (id, price, price_old, title, author_id) values (13, 2341, 1330, 'Redhold', 18);
insert into books (id, price, price_old, title, author_id) values (14, 1661, 1715, 'Bytecard', 1);
insert into books (id, price, price_old, title, author_id) values (15, 652, 3205, 'Tin', 13);
insert into books (id, price, price_old, title, author_id) values (16, 2127, 3785, 'Regrant', 4);
insert into books (id, price, price_old, title, author_id) values (17, 2569, 3806, 'Alphazap', 2);
insert into books (id, price, price_old, title, author_id) values (18, 2754, 1083, 'Pannier', 12);
insert into books (id, price, price_old, title, author_id) values (19, 565, 2295, 'Cardify', 3);
insert into books (id, price, price_old, title, author_id) values (20, 1545, 2027, 'Cardguard', 21);
insert into books (id, price, price_old, title, author_id) values (21, 1377, 3089, 'Matsoft', 19);
insert into books (id, price, price_old, title, author_id) values (22, 2714, 3931, 'Overhold', 2);
insert into books (id, price, price_old, title, author_id) values (23, 1364, 2489, 'Redhold', 16);
insert into books (id, price, price_old, title, author_id) values (24, 1705, 1565, 'Flowdesk', 6);
insert into books (id, price, price_old, title, author_id) values (25, 1507, 3196, 'Zaam-Dox', 5);
insert into books (id, price, price_old, title, author_id) values (26, 2146, 2549, 'Hatity', 17);
insert into books (id, price, price_old, title, author_id) values (27, 1131, 1376, 'Otcom', 7);
insert into books (id, price, price_old, title, author_id) values (28, 2918, 3615, 'Andalax', 3);
insert into books (id, price, price_old, title, author_id) values (29, 2197, 1598, 'Stim', 2);
insert into books (id, price, price_old, title, author_id) values (30, 2034, 3175, 'Treeflex', 19);
insert into books (id, price, price_old, title, author_id) values (31, 1576, 3116, 'Tresom', 15);
insert into books (id, price, price_old, title, author_id) values (32, 2448, 2325, 'Asoka', 8);
insert into books (id, price, price_old, title, author_id) values (33, 1403, 2228, 'Wrapsafe', 12);
insert into books (id, price, price_old, title, author_id) values (34, 2876, 1605, 'Temp', 6);
insert into books (id, price, price_old, title, author_id) values (35, 741, 1367, 'Greenlam', 20);
insert into books (id, price, price_old, title, author_id) values (36, 2265, 1357, 'Stronghold', 1);
insert into books (id, price, price_old, title, author_id) values (37, 2928, 1272, 'Zathin', 11);
insert into books (id, price, price_old, title, author_id) values (38, 827, 1110, 'Asoka', 10);
insert into books (id, price, price_old, title, author_id) values (39, 1855, 3441, 'It', 21);
insert into books (id, price, price_old, title, author_id) values (40, 774, 2200, 'Quo Lux', 20);
insert into books (id, price, price_old, title, author_id) values (41, 748, 1627, 'Fintone', 13);
insert into books (id, price, price_old, title, author_id) values (42, 2134, 3899, 'Veribet', 2);
insert into books (id, price, price_old, title, author_id) values (43, 2010, 3980, 'Prodder', 16);
insert into books (id, price, price_old, title, author_id) values (44, 2885, 1486, 'Tres-Zap', 14);
insert into books (id, price, price_old, title, author_id) values (45, 2634, 2123, 'Asoka', 13);
insert into books (id, price, price_old, title, author_id) values (46, 1394, 1894, 'Temp', 19);
insert into books (id, price, price_old, title, author_id) values (47, 2175, 3298, 'Home Ing', 1);
insert into books (id, price, price_old, title, author_id) values (48, 836, 3542, 'Matsoft', 18);
insert into books (id, price, price_old, title, author_id) values (49, 1220, 3262, 'Pannier', 16);
insert into books (id, price, price_old, title, author_id) values (50, 625, 2980, 'Asoka', 12);
insert into books (id, price, price_old, title, author_id) values (51, 2983, 2669, 'Quo Lux', 1);
insert into books (id, price, price_old, title, author_id) values (52, 2358, 1938, 'Zamit', 2);
insert into books (id, price, price_old, title, author_id) values (53, 2158, 2504, 'Sonair', 8);
insert into books (id, price, price_old, title, author_id) values (54, 1877, 3052, 'Greenlam', 21);
insert into books (id, price, price_old, title, author_id) values (55, 2353, 2383, 'Veribet', 1);
insert into books (id, price, price_old, title, author_id) values (56, 2873, 2705, 'Span', 10);
insert into books (id, price, price_old, title, author_id) values (57, 2451, 1004, 'Opela', 2);
insert into books (id, price, price_old, title, author_id) values (58, 2624, 2362, 'Konklab', 19);
insert into books (id, price, price_old, title, author_id) values (59, 2453, 2731, 'Viva', 1);
insert into books (id, price, price_old, title, author_id) values (60, 2419, 1194, 'Toughjoyfax', 4);
insert into books (id, price, price_old, title, author_id) values (61, 2053, 2992, 'Overhold', 11);
insert into books (id, price, price_old, title, author_id) values (62, 1703, 3800, 'Hatity', 8);
insert into books (id, price, price_old, title, author_id) values (63, 2807, 3756, 'Bigtax', 7);
insert into books (id, price, price_old, title, author_id) values (64, 2623, 1204, 'Gembucket', 10);
insert into books (id, price, price_old, title, author_id) values (65, 1490, 3034, 'Bitchip', 10);
insert into books (id, price, price_old, title, author_id) values (66, 1981, 2603, 'Redhold', 4);
insert into books (id, price, price_old, title, author_id) values (67, 1829, 2127, 'Home Ing', 11);
insert into books (id, price, price_old, title, author_id) values (68, 2275, 2701, 'Konklab', 2);
insert into books (id, price, price_old, title, author_id) values (69, 1140, 2730, 'Latlux', 5);
insert into books (id, price, price_old, title, author_id) values (70, 1899, 1948, 'Zathin', 11);
insert into books (id, price, price_old, title, author_id) values (71, 2935, 1001, 'Alpha', 5);
insert into books (id, price, price_old, title, author_id) values (72, 1238, 1157, 'Regrant', 20);
insert into books (id, price, price_old, title, author_id) values (73, 2963, 3240, 'Opela', 16);
insert into books (id, price, price_old, title, author_id) values (74, 2236, 2802, 'Tres-Zap', 4);
insert into books (id, price, price_old, title, author_id) values (75, 1943, 3685, 'Temp', 21);
insert into books (id, price, price_old, title, author_id) values (76, 1227, 3597, 'Mat Lam Tam', 10);
insert into books (id, price, price_old, title, author_id) values (77, 1730, 2368, 'Opela', 10);
insert into books (id, price, price_old, title, author_id) values (78, 1433, 3136, 'Mat Lam Tam', 13);
insert into books (id, price, price_old, title, author_id) values (79, 2360, 2886, 'Sub-Ex', 12);
insert into books (id, price, price_old, title, author_id) values (80, 1305, 1230, 'Zamit', 19);
insert into books (id, price, price_old, title, author_id) values (81, 2293, 1829, 'Tres-Zap', 19);
insert into books (id, price, price_old, title, author_id) values (82, 2102, 2493, 'Konklux', 11);
insert into books (id, price, price_old, title, author_id) values (83, 2154, 3645, 'Domainer', 15);
insert into books (id, price, price_old, title, author_id) values (84, 2876, 1739, 'Wrapsafe', 20);
insert into books (id, price, price_old, title, author_id) values (85, 2108, 3505, 'Treeflex', 18);
insert into books (id, price, price_old, title, author_id) values (86, 1660, 1876, 'Regrant', 13);
insert into books (id, price, price_old, title, author_id) values (87, 520, 3795, 'Zoolab', 8);
insert into books (id, price, price_old, title, author_id) values (88, 2585, 2414, 'Lotstring', 12);
insert into books (id, price, price_old, title, author_id) values (89, 1878, 1839, 'Lotstring', 6);
insert into books (id, price, price_old, title, author_id) values (90, 2789, 2421, 'Veribet', 1);
insert into books (id, price, price_old, title, author_id) values (91, 1131, 1060, 'Viva', 12);
insert into books (id, price, price_old, title, author_id) values (92, 2694, 1736, 'Konklux', 12);
insert into books (id, price, price_old, title, author_id) values (93, 1887, 2768, 'Zaam-Dox', 14);
insert into books (id, price, price_old, title, author_id) values (94, 2102, 3242, 'It', 19);
insert into books (id, price, price_old, title, author_id) values (95, 551, 3359, 'Flexidy', 1);
insert into books (id, price, price_old, title, author_id) values (96, 1948, 2607, 'Tempsoft', 15);
insert into books (id, price, price_old, title, author_id) values (97, 978, 3529, 'Sub-Ex', 21);
insert into books (id, price, price_old, title, author_id) values (98, 2976, 2988, 'Otcom', 8);
insert into books (id, price, price_old, title, author_id) values (99, 1853, 3936, 'Solarbreeze', 16);
insert into books (id, price, price_old, title, author_id) values (100, 670, 2494, 'It', 17);

update books set is_bestseller = false where author_id in (1,2);

commit;